title: Shirleen Simon
description: >-
  Data Analyst | Machine Learning | Python Enthusiast
baseurl: ""
url: "https://shirleensimon.github.io"
theme: jekyll-theme-minimal
logo: /assets/img/profile.jpg  # optional
github:
  is_project_page: false
